nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] # Corrected the origin URL
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
